### ISSUE TITLE
Add sql minimal dump for running application

### ISSUE THREAD

**Issue by Artiomtb** [rad9maza/Rader#2]
Add to resources folder script to initialize database (you sholud decide which database you would use).

**Comment by rad9maza** [comment]
Add scripts [create_tables.sql](https://github.com/rad9maza/Rader/blob/dev/src/main/resources/resources/create_tables.sql)  and [fill_tables.sql](https://github.com/rad9maza/Rader/blob/dev/src/main/resources/resources/fill_tables.sql)
